# Site settings
title: The Coding Sojourner
header-img: img/home-bg.png
email: bkhartmire@gmail.com
copyright_name: bkhartmire
description: > # this means to ignore newlines until "baseurl:"
  Didn't Feel Like a Travel Blog, So Here's a Coding One Instead
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bkhartmire
learn_profile: bkhartmire
email_username: bkhartmire@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
