# Site settings
author: Brittany Hartmire
title: The Vagabond Coder
header-img: img/home-bg.png
email: bkhartmire@gmail.com
copyright_name: Brittany Hartmire
description: > # this means to ignore newlines until "baseurl:"
  Didn't feel like writing a travel blog, so this one's about code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bkhartmire

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
